#ifndef __HARDWARE_SETTING_H__
#define __HARDWARE_SETTING_H__

#define FRONT_LEFT_JAGUAR_CANID  1
#define FRONT_RIGHT_JAGUAR_CANID 2
#define BACK_LEFT_JAGUAR_CANID   4
#define BACK_RIGHT_JAGUAR_CANID  3

#define DRIVE_STICK_PORT 1
#define CAM_STICK_PORT 2
#define DASH_BOARD_PORT 3

#define GYRO_PORT 1

#endif
