// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AngelDeployCommand.h"
#include "Commands/AngelIdleCommand.h"
#include "Commands/AngelUndeployCommand.h"
#include "Commands/ArticulatedActivateCommand.h"
#include "Commands/ArticulatedDeployCommand.h"
#include "Commands/ArticulatedExtendCommand.h"
#include "Commands/ArticulatedIdleCommand.h"
#include "Commands/ArticulatedInactivateCommand.h"
#include "Commands/ArticulatedUndeployCommand.h"
#include "Commands/ArticulatedUnextendCommand.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/CancelAllCommand.h"
#include "Commands/ClimbDistanceCommand.h"
#include "Commands/ClimbToLevelOneCommand.h"
#include "Commands/ClimbToLevelThreeCommand.h"
#include "Commands/ClimbToLevelTwoCommand.h"
#include "Commands/CompressorIdleCommand.h"
#include "Commands/CompressorStartCommand.h"
#include "Commands/CompressorStopCommand.h"
#include "Commands/DriveBrakeCommand.h"
#include "Commands/DriveDriveCommand.h"
#include "Commands/FeetDeployCommand.h"
#include "Commands/FeetIdleCommand.h"
#include "Commands/FeetUndeployCommand.h"
#include "Commands/FixedDeployCommand.h"
#include "Commands/FixedIdleCommand.h"
#include "Commands/FixedUndeployCommand.h"
#include "Commands/PneumaticsOff.h"
#include "Commands/ShooterIdleCommand.h"
#include "Commands/ShooterLoadCommand.h"
#include "Commands/ShooterShootCommand.h"
#include "Commands/ShooterStopCommand.h"
#include "Commands/StopAllCommand.h"
#include "Commands/TippingDeployCommand.h"
#include "Commands/TippingIdleCommand.h"
#include "Commands/TippingUndeployCommand.h"
#include "Commands/TrackDriveDownCommand.h"
#include "Commands/TrackDriveUpCommand.h"
#include "Commands/TrackIdleCommand.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI(): pad(1)
{
	xButton = new JoystickButton(&pad, Gamepad::kXButton);
	xButton->WhenPressed(new CompressorStartCommand());
	
	bButton = new JoystickButton(&pad, Gamepad::kBButton);
	bButton->WhenPressed(new CancelAllCommand());
	
	// Process operator interface input here.
	SmartDashboard::PutData("Compressor Automatic On", new CompressorIdleCommand(true));
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	SmartDashboard::PutData("Drive Drive Command", new DriveDriveCommand());
	SmartDashboard::PutData("Drive Brake Command", new DriveBrakeCommand());
	SmartDashboard::PutData("Shooter Idle Command", new ShooterIdleCommand());
	SmartDashboard::PutData("Shooter Shoot Command", new ShooterShootCommand());
	SmartDashboard::PutData("Shooter Load Command", new ShooterLoadCommand());
	SmartDashboard::PutData("Shooter Stop Command", new ShooterStopCommand());
	SmartDashboard::PutData("Track Idle Command", new TrackIdleCommand());
	SmartDashboard::PutData("Track Drive Down Command", new TrackDriveDownCommand());
	SmartDashboard::PutData("Track Drive Up Command", new TrackDriveUpCommand());
	SmartDashboard::PutData("Stop All Command", new StopAllCommand());
	SmartDashboard::PutData("Compressor Start Command", new CompressorStartCommand());
	SmartDashboard::PutData("Compressor Stop Command", new CompressorStopCommand());
	SmartDashboard::PutData("Fixed Deploy Command", new FixedDeployCommand());
	SmartDashboard::PutData("Fixed Undeploy Command", new FixedUndeployCommand());
	SmartDashboard::PutData("Fixed Idle Command", new FixedIdleCommand());
	SmartDashboard::PutData("Feet Deploy Command", new FeetDeployCommand());
	SmartDashboard::PutData("Feet Undeploy Command", new FeetUndeployCommand());
	SmartDashboard::PutData("Feet Idle Command", new FeetIdleCommand());
	SmartDashboard::PutData("Tipping Deploy Command", new TippingDeployCommand());
	SmartDashboard::PutData("Tipping Undeploy Command", new TippingUndeployCommand());
	SmartDashboard::PutData("Tipping Idle Command", new TippingIdleCommand());
	SmartDashboard::PutData("Articulated Idle Command", new ArticulatedIdleCommand());
	SmartDashboard::PutData("Articulated Deploy Command", new ArticulatedDeployCommand());
	SmartDashboard::PutData("Articulated Undeploy Command", new ArticulatedUndeployCommand());
	SmartDashboard::PutData("Articulated Extend Command", new ArticulatedExtendCommand());
	SmartDashboard::PutData("Articulated Unextend Command", new ArticulatedUnextendCommand());
	SmartDashboard::PutData("Articulated Activate Command", new ArticulatedActivateCommand());
	SmartDashboard::PutData("Articulated Inactivate Command", new ArticulatedInactivateCommand());
	SmartDashboard::PutData("Angel Idle Command", new AngelIdleCommand());
	SmartDashboard::PutData("Angel Deploy Command", new AngelDeployCommand());
	SmartDashboard::PutData("Angel Undeploy Command", new AngelUndeployCommand());
	SmartDashboard::PutData("Pneumatics Off", new PneumaticsOff());
	SmartDashboard::PutData("Cancel All Command", new CancelAllCommand());
	SmartDashboard::PutData("Climb To Level One Command", new ClimbToLevelOneCommand());
	SmartDashboard::PutData("Climb To Level Two Command", new ClimbToLevelTwoCommand());
	SmartDashboard::PutData("Climb To Level Three Command", new ClimbToLevelThreeCommand());
	SmartDashboard::PutData("Climb Distance Command", new ClimbDistanceCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
bool OI::GetPadButton(int type)
{
	return pad.GetRawButton(type);
}
float OI::getPadRawAxis(int axis)
{
	return pad.GetRawAxis(axis);
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
