// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
#include "Gamepad.hpp"
#include "XPad.h"
class OI {
private:
	//Logitech controller
	Gamepad pad;
	
	//Xbox Controller Buttons
	XPad xPad;
	JoystickButton* aButtonX;
	JoystickButton* rBumperButtonX;
	JoystickButton* lBumperButtonX;
	JoystickButton* xButtonX;
	JoystickButton* yButtonX;
	JoystickButton* bButtonX;
	JoystickButton* startButtonX;
	JoystickButton* backButtonX;
	JoystickButton* lStickButtonX;
	JoystickButton* rStickButtonX;
	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();
	float getPadRawAxis(int axis);
	bool getPadButton(int button);
	float getXPadRawAxis(int axis);
	bool getXPadButton(int button);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};
#endif
