// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
#include "Gamepad.hpp"
#include "XPad.h"
class OI {
private:
	Gamepad pad;
	JoystickButton* xButton;
	JoystickButton* yButton;
	JoystickButton* bButton;
	JoystickButton* aButton;
	JoystickButton* rtButton;
	JoystickButton* startButton;
	JoystickButton* backButton;
	JoystickButton* rBumperButton;
	JoystickButton* lBumperButton;
	JoystickButton* lTriggerButton;
	JoystickButton* rTriggerButton;
	JoystickButton* lStickButton;
	JoystickButton* rStickButton;
	
	Joystick stickOne;
	JoystickButton *stickOneTriggerButton;
	JoystickButton *stickOnestickOneButtonTwo;
	JoystickButton *stickOneButtonTwo;
	JoystickButton *stickOneButtonThree;
	JoystickButton *stickOneButtonFour;
	JoystickButton *stickOneButtonFive;
	JoystickButton *stickOneButtonSix;
	JoystickButton *stickOneButtonSeven;
	JoystickButton *stickOneButtonEight;
	JoystickButton *stickOneButtonNine;
	JoystickButton *stickOneButtonTen;
	JoystickButton *stickOneButtonEleven;
	JoystickButton *stickOneButtonTwelve;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();
	float getPadRawAxis(int axis);
	bool GetPadButton(int button);
	float getBigStickX();
	float getBigStickY();
	float getBigStickZ();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};
#endif
