// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "Arduino.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	static Relay* compressorRelay;
	static DigitalInput* highPressureLimitSensor;
	static Arduino_I2C* arduino;
	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static CANJaguar* driveCANJaguar1;
	static CANJaguar* driveCANJaguar2;
	static CANJaguar* driveCANJaguar3;
	static CANJaguar* driveCANJaguar4;
	static RobotDrive* driveRobotDrive41;
	static Encoder* driveEncoder1;
	static Encoder* driveQuadratureEncoder2;
	static Encoder* driveQuadratureEncoder3;
	static Encoder* driveQuadratureEncoder4;
	static DigitalInput* driveDigitalInput1;
	static DoubleSolenoid* shooterDoubleSolenoid1;
	static Encoder* trackQuadratureEncoder1;
	static Encoder* trackQuadratureEncoder2;
	static SpeedController* trackSpeedController1;
	static SpeedController* trackSpeedController2;
	static Solenoid* angelWingsSolenoid1;
	static Solenoid* tippingSolenoid1;
	static CANJaguar* articulatingArmCANJaguar1;
	static Encoder* articulatingArmQuadratureEncoder1;
	static DigitalInput* articulatingArmDigitalInput1;
	static Solenoid* articulatingArmSolenoid1;
	static DigitalInput* fixedArmDigitalInput1;
	static Solenoid* fixedArmSolenoid1;
	static DigitalInput* feetDigitalInput1;
	static DigitalInput* feetDigitalInput2;
	static Solenoid* feetSolenoid1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
