// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	static Relay* compressorRelay;
	static Relay* articulatingRelay;

	//Can the following be organized at all? It's kind of all over the place...
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static CANJaguar* driveCANJaguar1;
	static CANJaguar* driveCANJaguar2;
	static CANJaguar* driveCANJaguar3;
	static CANJaguar* driveCANJaguar4;
	static RobotDrive* driveRobotDrive41;
	static Gyro* driveGyro1;
	static CANJaguar* shooterCANJaguar1;
	static DoubleSolenoid* shooterLoaderSolenoid;
	static Encoder* trackQuadratureEncoder1;
	static AnalogChannel* trackAnalogForce1;
	static AnalogChannel* trackAnalogForce2;
	static Solenoid* trackBrakeSolenoid;
	static SpeedController* trackSpeedController1;
	static SpeedController* trackSpeedController2;
	static Solenoid* tippingSolenoid1;
	static DigitalInput* tippingDigitalIRSensor;
	static CANJaguar* articulatingArmCANJaguar1;
	static DigitalInput* articulatingArmDeployLimit;
	static DigitalInput* articulatingArmUndeployLimit;
	static DoubleSolenoid* articulatingArmDoubleSolenoid1;
	static AnalogChannel* articulatingArmSlidePetentiometer;
	static DigitalInput* fixedArmDeployLimit;
	static DigitalInput* fixedArmUndeployLimit;
	static Solenoid* feetSolenoid1;
	static AnalogChannel* feetAnalogForce2;
	static DigitalInput* feetFeetLimit1;
	static DigitalInput* pneumaticsCompressorDigitalInput1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
