// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ClimbDistanceCommand.h"
ClimbDistanceCommand::ClimbDistanceCommand(float distance) 
{
	m_distance = distance;
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::track);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void ClimbDistanceCommand::Initialize() 
{
	
}
// Called repeatedly when this Command is scheduled to run
void ClimbDistanceCommand::Execute() 
{
	RobotMap::trackSpeedController1->Set(0.5);
	RobotMap::trackSpeedController2->Set(0.5);
}
// Make this return true when this Command no longer needs to run execute()
bool ClimbDistanceCommand::IsFinished() 
{
	return true; //(RobotMap::trackQuadratureEncoder1 + RobotMap::trackQuadratureEncoder2 > m_distance * conversion factor);
}
// Called once after isFinished returns true
void ClimbDistanceCommand::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ClimbDistanceCommand::Interrupted() {
}
