// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Feet.h"
#include "../Robotmap.h"
#include "../Commands/FeetIdleCommand.h"
Feet::Feet() : Subsystem("Feet") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	solenoid1 = RobotMap::feetSolenoid1;
	analogForce2 = RobotMap::feetAnalogForce2;
	feetLimit1 = RobotMap::feetFeetLimit1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Feet::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new FeetIdleCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
bool Feet::FeetAreTouching()
{
	return ( feetLimit1->Get() && analogForce2->GetVoltage() > 3.5);//FIXME Set the correct sensor value
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
